import { Calendar, DollarSign, Trophy, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import contestData from "../../../demoData/contestsData.json";
import SubmitModal from "./SubmitModal";
import { motion } from "framer-motion";
import { Calendar, DollarSign, Trophy, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import contestData from "../../../demoData/contestsData.json";
import SubmitModal from "./SubmitModal";
